# Generated by Django 5.1.3 on 2026-01-12 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('ru_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(max_length=64)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='parmodels.building')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parmodels.location')),
            ],
        ),
        migrations.CreateModel(
            name='IfcModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('ifc_file_path', models.TextField()),
                ('ifc_sha256', models.CharField(max_length=64, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='uploaded', max_length=32)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifc_models', to='parmodels.building')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifc_models', to='parmodels.location')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='parmodels.user')),
            ],
        ),
        migrations.CreateModel(
            name='ModelElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifc_id', models.IntegerField(blank=True, null=True)),
                ('global_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('element_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='parmodels.elementtype')),
                ('ifc_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='parmodels.ifcmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ifc_model', 'global_id'), name='uq_model_elements_model_global')],
            },
        ),
    ]
