# Generated by Django 5.1.3 on 2026-01-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parmodels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifcmodel',
            name='ifc_file_path',
        ),
        migrations.AddField(
            model_name='ifcmodel',
            name='ifc_file',
            field=models.FileField(blank=True, null=True, upload_to='ifc/'),
        ),
    ]
