# Generated by Django 5.1.3 on 2026-01-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parmodels', '0002_remove_ifcmodel_ifc_file_path_ifcmodel_ifc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifcmodel',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='parmodels.user'),
        ),
    ]
