# Generated by Django 5.1.3 on 2026-01-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parmodels', '0003_alter_ifcmodel_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifcmodel',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
