# Generated by Django 5.1.3 on 2026-01-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parmodels', '0004_ifcmodel_is_parsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifcmodel',
            name='ifc_sha256',
            field=models.CharField(max_length=64),
        ),
    ]
