# Generated by Django 5.1.3 on 2026-05-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parmodels', '0010_migrate_legacy_buildings_ifc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='building',
        ),
        migrations.RemoveField(
            model_name='ifcmodel',
            name='building',
        ),
        migrations.RemoveField(
            model_name='modelelement',
            name='element_type',
        ),
        migrations.RemoveField(
            model_name='ifcmodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ifcmodel',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='modelelement',
            name='ifc_model',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='ElementType',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='IfcModel',
        ),
        migrations.DeleteModel(
            name='ModelElement',
        ),
    ]
