# Generated by Django 5.1.3 on 2026-05-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parmodels', '0011_remove_location_building_remove_ifcmodel_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpriority',
            name='color_code',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='color_code',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
